server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost/dss
    username: root
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect

service:
  secret-key: 'desarrolloSoftwareSeguro'